version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: backend
    ports:
      - "3002:3002"
    volumes:
      - ./:/usr/political-capital-two:rw
    working_dir: /usr/political-capital-two/packages/backend
    command: yarn dev
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/political-capital-two:rw
    working_dir: /usr/political-capital-two/packages/frontend
    command: yarn dev
  database:
    image: yugabytedb/yugabyte:latest
    container_name: database
    ports:
      - "7001:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    volumes:
      - ./yb_data:/home/yugabyte/yb_data
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
    
