version: "3.9"

services:
  political_capital_two:
    image: node:18
    container_name: political_capital_two
    ports:
      - "3000:3000"  # frontend
      - "3002:3002"  # backend
      - "3003:3003"  # websockets
    volumes:
      - ./:/usr/political-capital-two:rw
    working_dir: /usr/political-capital-two
    command: yarn dev
    environment:
      - ORIGIN=0.0.0.0
      - DATABASE_HOST=host.docker.internal
  database:
    image: yugabytedb/yugabyte:latest
    container_name: database
    ports:
      - "7001:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server
