version: "3.9"

services:
  political_capital_twp:
    image: node:18
    container_name: political_capital_two
    ports:
      - "3000:3000"
      - "3002:3002"
    volumes:
      - ./:/usr/political-capital-two:rw
    working_dir: /usr/political-capital-two
    command: yarn dev
    environment:
      - ORIGIN=0.0.0.0
  database:
    image: yugabytedb/yugabyte:latest
    container_name: database
    ports:
      - "7001:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    volumes:
      - ./yb_data:/home/yugabyte/yb_data
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
    
